### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by costanzomoffa** [ErnadoO/ext-phpbb-directory#33]
hi i have this error message when activated this ext 

i have another ext on my forum phpbb 3.2.2

`Fatal error: Uncaught Twig_Error_Loader: Unable to find template "blocks/menu_block.html" (looked into: /home3/costanzo/public_html/phpBB3/styles/prosilver/template, /home3/costanzo/public_html/phpBB3/styles/prosilver/theme, /home3/costanzo/public_html/phpBB3/styles/all/template). in /home3/costanzo/public_html/phpBB3/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:232 Stack trace: #0 /home3/costanzo/public_html/phpBB3/phpbb/template/twig/loader.php(135): Twig_Loader_Filesystem->findTemplate('blocks/menu_blo...') #1 /home3/costanzo/public_html/phpBB3/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(150): phpbbtemplatetwigloader->findTemplate('blocks/menu_blo...') #2 /home3/costanzo/public_html/phpBB3/vendor/twig/twig/lib/Twig/Environment.php(329): Twig_Loader_Filesystem->getCacheKey('blocks/menu_blo...') #3 /home3/costanzo/public_html/phpBB3/vendor/twig/twig/lib/Twig/Environment.php(419): Twig_Environment->getTemplateClass('blocks/menu_blo...') #4 /home3/costanzo/public_html/phpBB3/phpbb/template/twig/environment.php(27 in /home3/costanzo/public_html/phpBB3/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 232`

**Comment by ErnadoO** [comment]
Hi

blocks/menu_block is not a file of my extension, your problem is not related to my extension.

try to install another extension, you will have, i think, the same error

**Comment by costanzomoffa** [comment]
hi i try but i have this error ony with cbb_blockets and phpbb-directory
i don't know why.
